### ISSUE TITLE
Incorrect instance passed to addTags method of FixedTaggingCachePool

### ISSUE THREAD

**Issue by vpassapera** [php-cache/issues#100]
Given the following json composer deps:
```json
    "require": {
        "php": ">=7.0",
        "ext-redis": "*",
        "symfony/symfony": "~3.2",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "doctrine/doctrine-migrations-bundle": "^1.2",
        "stof/doctrine-extensions-bundle": "^1.2",
        "league/tactician-doctrine": "^1.0",
        "ramsey/uuid-doctrine": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "~2.11.3",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "league/tactician-bundle": "^0.4",
        "friendsofsymfony/rest-bundle": "dev-master as 2.6",
        "nelmio/api-doc-bundle": "^2.11",
        "jms/serializer-bundle": "^1.1",
        "jms/di-extra-bundle": "^1.8",
        "guzzlehttp/guzzle": "6.2.2",
        "mopa/bootstrap-bundle": "~3.0",
        "twbs/bootstrap": "~3.3.0",
        "symfony/assetic-bundle": "^2.8",
        "friendsofsymfony/jsrouting-bundle": "^1.6",
        "bmatzner/fontawesome-bundle": "~4.7",
        "danielstjules/stringy": "dev-master as 2.3.3",
        "tdn/php-types": "dev-develop as 3.0.0",
        "kzykhys/git": "v0.1.2",
        "cache/apcu-adapter": "~0.2",
        "cache/redis-adapter": "~0.4",
        "cache/cache-bundle": "~0.4",
        "cache/adapter-bundle": "~0.4",
        "cache/psr-6-doctrine-bridge": "~2.2",
        "kachkaev/assets-version-bundle": "~2.0",
        "components/jquery": "~3.1",
        "components/jqueryui": "~1.12",
        "datatables/datatables": "~1.10",
        "e-moe/guzzle6-bundle": "~1.1",
        "composer/semver": "^1.4",
        "paquettg/php-html-parser": "~1.7",
        "verbalexpressions/php-verbal-expressions": "dev-master",
        "php-amqplib/php-amqplib": "^2.6",
        "php-amqplib/rabbitmq-bundle": "^1.8"
    },
```
Config:

```yml
cache_adapter:
    providers:
        sauron_apcu:
            factory: 'cache.factory.apcu'
            options: []
            aliases: ['app.apcu_cache']

        sauron_redis_cache:
            factory: 'cache.factory.redis'
            options:
                host: 127.0.0.1
                port: 6379
            aliases: ['app.redis_cache']

cache:
    doctrine:
        enabled: true
        use_tagging: true
        metadata:
            service_id: 'app.redis_cache'
            entity_managers:   [ default ]       # the name of your entity_manager connection
            document_managers: [ default ]       # the name of your document_manager connection
        result:
            service_id: 'app.redis_cache'
            entity_managers:   [ default, read ] # you may specify multiple entity_managers
        query:
            service_id: 'app.redis_cache'
            entity_managers: [ default ]
    annotation:
        enabled: true
        service_id: 'app.apcu_cache'
        use_tagging: true
    serializer:
        enabled: true
        service_id: 'app.apcu_cache'
        use_tagging: true
```

Dependencies install fine, however I get the following error when clearing symfony cache.

```
  [RuntimeException]                                                                                                                   
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                            
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Cache\CacheBundl  
  e\Cache\FixedTaggingCachePool::addTags() must be an instance of Cache\Taggable\TaggableItemInterface, instance of Cache\Adapter\Com  
  mon\CacheItem given, called in /vagrant/vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php on line 100 in /vagrant/vendo  
  r/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php:118                                                                         
  Stack trace:                                                                                                                         
  #0 /vagrant/vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php(100): Cache\CacheBundle\Cache\FixedTaggingCachePool->addT  
  ags(Object(Cache\Adapter\Common\CacheItem))                                                                                          
  #1 /vagrant/vendor/cache/psr-6-doctrine-bridge/DoctrineCacheBridge.php(97): Cache\CacheBundle\Cache\FixedTaggingCachePool->save(Obj  
  ect(Cache\Adapter\Common\CacheItem))                                                                                                 
  #2 /vagrant/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(132): Cache\Bridge\DoctrineCacheBridge->doSave('[AppB  
  undle\\Enti...', Array, NULL)                                                                                                        
  #3 /vagrant/vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/Extensio in /vagrant/vendor/cache/cache-bundle/src/Cache/FixedTaggin  
  gCachePool.php on line 118       
```

The issue is:

```php

    /**
     * {@inheritdoc}
     */
    public function save(CacheItemInterface $item)
    {
        $this->addTags($item);

        return $this->cache->save($item);
    }

   [...]

    /**
     * @param TaggableItemInterface $item
     */
    private function addTags(TaggableItemInterface $item)
    {
        foreach ($this->tags as $tag) {
            $item->addTag($tag);
        }
    }
```

Fix is:

```php
    /**
     * {@inheritdoc}
     */
    public function save(CacheItemInterface $item)
    {
        if ($item instanceof TaggableItemInterface) {
            $this->addTags($item);
        }

        return $this->cache->save($item);
    }
```

Opening PR.
