### ISSUE TITLE
Class Memcached not found

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#133]
Hello, I have the following installed with Symfony4

```
"cache/adapter-bundle": "^1.2",
"cache/cache-bundle": "^1.1",
"cache/doctrine-adapter": "^1.0",
"cache/memcached-adapter": "^1.0",
"cache/psr-6-doctrine-bridge": "^3.0",
```
And this config

```
cache:
    session:
        enabled: "%env(bool:SESSION_CACHE_ENABLED)%"
        service_id: "cache.provider.default_memcached"
        use_tagging: true
        ttl: 7200
    router:
        enabled: "%env(bool:ROUTER_CACHE_ENABLED)%"
        service_id: "cache.provider.default_memcached"
        ttl: 86400
    logging:
        enabled: "%env(bool:APP_DEBUG)%"
        logger: "logger"
        #level: "info"

    doctrine:
        enabled: "%env(bool:DOCTRINE_CACHE_ENABLED)%"
        use_tagging: false
        metadata:
          service_id: 'cache.provider.default_memcached'
          entity_managers:   [ default ]       # the name of your entity_manager connection
          document_managers: [ default ]       # the name of your document_manager connection
        result:
          service_id: 'cache.provider.default_memcached'
          entity_managers:   [ default, read ] # you may specify multiple entity_managers
        query:
          service_id: 'cache.provider.default_memcached'
          entity_managers: [ default ]

cache_adapter:
    providers:
        default_memcached:
            factory: cache.factory.memcached
            options:
                host: localhost
                port: 11211
```

on cache:clear I get the following errors

```
Fatal error: Class 'Memcached' not found in /Users/patricklock/Sites/HeliosSf4/vendor/cache/adapter-bundle/src/ProviderHelper/Memcached.php on line 19
Fatal error: Class 'Memcached' not found in /Users/patricklock/Sites/HeliosSf4/vendor/doctrine/doctrine-cache-bundle/Tests/Functional/Fixtures/Memcached.php on line 6
```

If I go to either of those classes in PHP Storm I can click through to the \Memcached class. I also have memcached enabled in MAMP and can see it enabled in phpinfo.
