### ISSUE TITLE
Symfony debug toolbar not shown - profiler template not found

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#134]
I am using Symfony 4 with the following

```
"cache/adapter-bundle": "^1.2",
"cache/cache-bundle": "^1.1",
"cache/doctrine-adapter": "^1.0",
"cache/memcached-adapter": "^1.0",
"cache/psr-6-doctrine-bridge": "^3.0",
```

When loading a page the debug toolbar shows with "An error occurred while loading the web debug toolbar."

The template is specified in vendor/cache/cache-bundle/Resources/config/data-collector.yml
The template exists in vendor/cache/cache-bundle/Resources/views/Collector/cache.html.twig

```
cache.data_collector:
    class: Cache\CacheBundle\DataCollector\CacheDataCollector
    tags:
      - { name: data_collector, template: 'CacheBundle:Collector:cache.html.twig', id: 'php-cache' }
```

`request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "The profiler template "@CacheBundle/Resources/views/Collector/cache.html.twig" for data collector "php-cache" does not exist."`
