### ISSUE TITLE
Fallback in case connection fail

### ISSUE THREAD

**Issue by choks87** [php-cache/issues#135]
It would be good if we could have a fallback adapter (NullAdapter) in the case when some adapter fails to connect. 

Ex. if Redis adapter throws ConnectionException and if the fallback option is set, no exception is thrown, but it will use NullAdapter.

Right now, if Redis is not available, app dies.
This could be achieved by adding some listeners directly in the app, and catch block, but if autowiring is used, it will fail.

example config:
```
cache_adapter:
    fallback_provider: @cache.provider.void
    providers:
        redis:
            factory: cache.factory.redis
            options:
                host: '%env(REDIS_HOST)%'
                port: '%env(REDIS_PORT)%'
         void:
            factory: cache.factory.void
```
