### ISSUE TITLE
cache clear throws You have requested a non-existent service “cache.proxy_factory” in prod environment

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#137]
I am deploying a Symfony4 app. After composer install when cache:clear is run it throws the following error:

`In ContainerBuilder.php line 1011: You have requested a non-existent service "cache.proxy_factory".`

The vendors installed correctly but I can't clear the cache.

vendors are installed with

`sudo SYMFONY_ENV=prod composer install -d=/var/www/html --no-dev --no-interaction --optimize-autoloader --verbose --profile --prefer-dist`

I get the same error if I run cache:clear manually with

`php bin/console cache:clear --env=prod`

I only have this issue with the prod environment. It is fine with staging on the same server.

I can even reproduce the same error on my local machine

**Comment by PaddyLock** [comment]
I have discovered this is related to my fix for #134 

I had put the fix in config/services.yaml like this

```
services:
    # override for temp fix - https://github.com/php-cache/issues/issues/134
    cache.data_collector:
        class: Cache\CacheBundle\DataCollector\CacheDataCollector
        tags:
          - { name: data_collector, template: '@WebProfiler/Collector/cache', id: 'php-cache' }
```

However, I should have put it in config/dev/services.yaml

When I cleared the cache for prod it somehow made the `vendor/cache/cache-bundle/Resources/config/data-collector.yml` invalid and so could not find the cache.proxy_factory service later down the file.
