### ISSUE TITLE
Invalid key Uncaught PHP Exception

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#49]
Hi, I am getting what appears to be random Critical error messages from time to time on our live environment such as this (domain name replaced):

request.CRITICAL: Uncaught PHP Exception Cache\Adapter\Common\Exception\InvalidArgumentException: "Invalid key: "www.mydomain.co.uk__.https:..maps.google.co.uk.maps__GET__f=q". The key contains one or more characters reserved for future extension: {}()/\@:" at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php line 241 {"exception":"[object] (Cache\\Adapter\\Common\\Exception\\InvalidArgumentException(code: 0): Invalid key: \"www.mydomain.co.uk__.https:..maps.google.co.uk.maps__GET__f=q\". The key contains one or more characters reserved for future extension: {}()/\\@: at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php:241)"} []

and this:

request.CRITICAL: Uncaught PHP Exception Cache\Adapter\Common\Exception\InvalidArgumentException: "Invalid key: "www.mydomain.co.uk__.index.php__GET__q=user/register". The key contains one or more characters reserved for future extension: {}()/\@:" at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php line 241 {"exception":"[object] (Cache\\Adapter\\Common\\Exception\\InvalidArgumentException(code: 0): Invalid key: \"www.mydomain.co.uk__.index.php__GET__q=user/register\". The key contains one or more characters reserved for future extension: {}()/\\@: at /var/www/releases/20160317121445/vendor/cache/adapter-common/src/AbstractCachePool.php:241)"} []

In the second case it looks like it is because of the forward slash, but I don't know about the first one. More interestingly I don't have an index.php so why is that in there? Is this a bug in the router cache?

Thanks

**Comment by Nyholm** [comment]
Hi. 

Thank you for this issue. You are using invalid keys. In the first case you have a colon (:) and in the second case you use a forward slash (/). 

Are you using the cache bundle? It seams that it is something wrong with our normalizer that should remove those characters.

**Comment by PaddyLock** [comment]
Hi, thanks for your quick response. I am using the following

```
"cache/doctrine-adapter": "0.4",
"cache/psr-6-doctrine-bridge": "^2.0.1",
"cache/cache-bundle": "0.3.1",
"cache/adapter-bundle": "^0.1",
"cache/memcached-adapter": "^0.2.0",
```

With this config

```
cache_adapter:
  providers:
    default_memcached:
      factory: cache.factory.memcached
      options:
        host: localhost
        port: 11211

cache:
  doctrine:
    enabled: true
    metadata:
      service_id: 'cache.provider.default_memcached'
      entity_managers:   [ default ]       # the name of your entity_manager connection
      document_managers: [ default ]       # the name of your document_manager connection
    result:
      service_id: 'cache.provider.default_memcached'
      entity_managers:   [ default, read ] # you may specify multiple entity_managers
    query:
      service_id: 'cache.provider.default_memcached'
      entity_managers: [ default ]
  router:
    enabled: true
    service_id: cache.provider.default_memcached
    ttl: 86400
```

**Comment by Nyholm** [comment]
Can you try the patch and tell me it it works better for you?

**Comment by PaddyLock** [comment]
Thanks, how do I apply a patch please?

**Comment by Nyholm** [comment]
`composer require cache/cache-bundle:dev-normalizer`

**Comment by PaddyLock** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: cache/taggable-cache[0.4.0, 0.3.1].
    - Can only install one of: cache/taggable-cache[0.4.0, 0.3.1].
    - Can only install one of: cache/taggable-cache[0.4.0, 0.3.1].
    - cache/cache-bundle dev-normalizer requires cache/taggable-cache ^0.4 -> satisfiable by cache/taggable-cache[0.4.0].
    - Installation request for cache/cache-bundle dev-normalizer -> satisfiable by cache/cache-bundle[dev-normalizer].
    - Installation request for cache/taggable-cache == 0.3.1.0 -> satisfiable by cache/taggable-cache[0.3.1].

**Comment by Nyholm** [comment]
I believe you need to bump the version of memcached adapter to the latest stable as well.

**Comment by PaddyLock** [comment]
I have bumped all my packages

`composer require cache/doctrine-adapter:0.5.* cache/psr-6-doctrine-bridge:2.1.* cache/cache-bundle:dev-normalizer cache/adapter-bundle:0.3.* cache/memcached-adapter:0.3.*`

now I get

```
Problem 1
    - Conclusion: remove cache/cache-bundle dev-normalizer
    - Installation request for cache/cache-bundle dev-normalizer -> satisfiable by cache/cache-bundle[dev-normalizer].
    - Conclusion: don't install cache/taggable-cache 0.3.1
    - cache/cache-bundle dev-normalizer requires cache/taggable-cache ^0.4 -> satisfiable by cache/taggable-cache[0.4.0].
    - Can only install one of: cache/taggable-cache[0.4.0, 0.3.1].
    - Can only install one of: cache/taggable-cache[0.3.1, 0.4.0].
    - Installation request for cache/taggable-cache == 0.3.1.0 -> satisfiable by cache/taggable-cache[0.3.1].
```

**Comment by PaddyLock** [comment]
I have finally got an installable set of packages with the following:

```
"cache/doctrine-adapter": "0.5.*",
"cache/psr-6-doctrine-bridge": "2.1.*",
"cache/cache-bundle": "dev-normalizer",
"cache/adapter-bundle": "0.3.*",
"cache/memcached-adapter": "0.3.*",
"cache/taggable-cache": "0.4.*",
"cache/hierarchical-cache": "0.2.1",
"cache/adapter-common": "0.3.0"
```

However, I know get this error when clearing the cache:

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'`

**Comment by PaddyLock** [comment]
On further investigation, the reason my Gedmo Slug extension is not working is because the cache is not clearing. The reason the cache is not clearing is because of the warning:

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'`

In the following method in Cache\CacheBundle\CommandCacheFlushCommand

```
private function clearTypedCacheFromService($type, $serviceId)
    {
        /** @type \Psr\Cache\CacheItemPoolInterface $service */
        $service = $this->getContainer()->get($serviceId);
        if ($service instanceof TaggablePoolInterface) {
            return $service->clearTags([$type]);
        } else {
            return $service->clear();
        }
    }
```

If I temporarily return `$service->clear();` then I can get the cache to clear. However, after returning the code to it's original state and then running my web application, I then get the following:

Argument 1 passed to Cache\CacheBundle\Cache\FixedTaggingCachePool::__construct() must be an instance of Cache\Taggable\TaggablePoolInterface, instance of Cache\Adapter\Memcached\MemcachedCachePool given, called in /***********/vendor/cache/cache-bundle/src/Factory/DoctrineBridgeFactory.php on line 33 and defined', '/*******/vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php', '41', array()) in FixedTaggingCachePool.php line 41

**Comment by PaddyLock** [comment]
I'm not sure why tagging is a requirement anyway, as I am not using tagging myself

**Comment by PaddyLock** [comment]
So, Cache\Adapter\Memcached\MemcachedCachePool does not implement TaggablePoolInterface. However, in Cache\CacheBundle\Command\CacheFlushCommand -> clearTypedCacheFromService() the service IS an instance of TaggablePoolInterface although when I dump $service here I get

```
Cache\CacheBundle\Cache\RecordingCachePool {#450
  -calls: []
  -cachePool: Cache\Adapter\Memcached\MemcachedCachePool {#446
    -cache: Memcached {#449}
    #deferred: []
    -keyCache: []
  }
}
```

**Comment by PaddyLock** [comment]
I have opened a different issue here #50

**Comment by PaddyLock** [comment]
@Nyholm The original patch for cache/cache-bundle:dev-normalizer worked, thanks!

**Comment by PaddyLock** [comment]
I have just upgraded to the following set of packages:

`
        "cache/doctrine-adapter": "0.5.0",
        "cache/psr-6-doctrine-bridge": "2.2.0",
        "cache/cache-bundle": "0.4.4",
        "cache/adapter-bundle": "0.4.0",
        "cache/memcached-adapter": "0.3.2",
`

and I am still getting this error when clearing the cache:

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'`

I have the following config:

```
cache:
  doctrine:
    enabled: true
    use_tagging: true
    metadata:
      service_id: 'cache.provider.default_memcached'
      entity_managers:   [ default ]       # the name of your entity_manager connection
      document_managers: [ default ]       # the name of your document_manager connection
    result:
      service_id: 'cache.provider.default_memcached'
      entity_managers:   [ default, read ] # you may specify multiple entity_managers
    query:
      service_id: 'cache.provider.default_memcached'
      entity_managers: [ default ]
```
