### ISSUE TITLE
Memcached TaggablePoolInterface expected MemcachedCachePool given

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#50]
When I try to clear the cache using `app/console cache:flush all` I get the following warning:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'

In the following method in Cache\CacheBundle\CommandCacheFlushCommand

```
private function clearTypedCacheFromService($type, $serviceId)
    {
        /** @type \Psr\Cache\CacheItemPoolInterface $service */
        $service = $this->getContainer()->get($serviceId);
        if ($service instanceof TaggablePoolInterface) {
            return $service->clearTags([$type]);
        } else {
            return $service->clear();
        }
    }
```

Cache\Adapter\Memcached\MemcachedCachePool does not implement TaggablePoolInterface. However, in Cache\CacheBundle\Command\CacheFlushCommand -> clearTypedCacheFromService() the service IS an instance of TaggablePoolInterface although when I dump $service here I get

Cache\CacheBundle\Cache\RecordingCachePool {#450
  -calls: []
  -cachePool: Cache\Adapter\Memcached\MemcachedCachePool {#446
    -cache: Memcached {#449}
    #deferred: []
    -keyCache: []
  }
}

If I temporarily return $service->clear(); then I can get the cache to clear. However, after returning the code to it's original state and then running my web application, I then get the following:

`Argument 1 passed to Cache\CacheBundle\Cache\FixedTaggingCachePool::__construct() must be an instance of Cache\Taggable\TaggablePoolInterface, instance of Cache\Adapter\Memcached\MemcachedCachePool given, called in /***********/vendor/cache/cache-bundle/src/Factory/DoctrineBridgeFactory.php on line 33 and defined', '/*******/vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php', '41', array()) in FixedTaggingCachePool.php line 41`

I'm not sure why tagging is a requirement anyway, as I am not using tagging myself.

**Comment by PaddyLock** [comment]
I think the solution is that `Cache\Adapter\Memcached\MemcachedCachePool` needs to `implements TaggablePoolInterface` ?

and then implement clearTags()

However, I am not sure what needs to be in clearTags()

Is this something that will be in a coming release?

I have hacked this file locally and it seems to work with an empty clearTags method, as I am not using tags.

**Comment by Nyholm** [comment]
Thank you for this detailed bug report. 
It seams like there is an issue with the RecordignCachePool. It is always an instance of TaggablePoolInterface and that is why the check always validates to true.. I will investigate further to find a solution.

**Comment by PaddyLock** [comment]
As a bit of extra info these are the packages I have

        ```
        "cache/doctrine-adapter": "0.5.*",
        "cache/psr-6-doctrine-bridge": "2.1.*",
        "cache/cache-bundle": "dev-normalizer",
        "cache/adapter-bundle": "0.3.*",
        "cache/memcached-adapter": "dev-master",
        "cache/taggable-cache": "0.4.*",
        "cache/hierarchical-cache": "0.2.1",
        "cache/adapter-common": "0.3.0"
```

**Comment by morgangiraud** [comment]
This is a bigger problem.
Since the last packagist upgrade (in my case):
- cache/adapter-bundle: 0.3.2 -> 0.3.3
- cache/adapter-common: 0.2.1 -> 0.3.0
- cache/hierarchical-cache: 0.2.0 -> 0.2.1
- cache/memcached-adapter: 0.2.0 -> 0.3.1
- cache/taggable-cache: 0.3.1 -> 0.4.0

It also broke a completely unrelated commands (assets:dump from assetic) due to the doctrineBridge getting loaded.

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Cache\CacheBundle\Cache\FixedTaggingCachePool::__construct()
must be an instance of Cache\Taggable\TaggablePoolInterface,
instance of Cache\Adapter\Memcached\MemcachedCachePool given, 
called in vendor/cache/cache-bundle/src/Factory/DoctrineBridgeFactory.php on line 33 
and defined in vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php:41
```

Hope it will helps you solve this deps problems, seems definitely like someone is not implementing the right interface.

**Comment by Nyholm** [comment]
Have you tried the fix in the linked PR?
https://github.com/php-cache/cache-bundle/pull/57

**Comment by morgangiraud** [comment]
Cool, my deployment script and my app is working again in preproduction (should be allright in production).

Thanks, that was fast!

**Comment by ajtis** [comment]
Try to create cache pool (chain)
```
cache_adapter:
    providers:
        my_memcached:
            factory: 'cache.factory.memcached'
            aliases: ['cache.memcached']
            options:
                host: 172.17.0.3 # Using custom host
                port: 11211
        my_chain:
            factory: 'cache.factory.chain'
            options:
                services:
                    - @cache.provider.my_memcached
cache:
    doctrine:
        enabled: true
        metadata:
            service_id: 'cache.provider.my_chain'
            entity_managers:   [ default ]       # the name of your entity_manager connection
            document_managers: [ default ]       # the name of your document_manager connection
        result:
            service_id: 'cache.provider.my_chain'
            entity_managers:   [ default, read ] # you may specify multiple entity_managers
        query:
            service_id: 'cache.provider.my_chain'
            entity_managers: [ default ]
```

composer includes:
```

        "cache/cache-bundle": "^0.4.1",
        "cache/adapter-bundle": "^0.3.3",
        "cache/psr-6-doctrine-bridge": "^2.1",
        "cache/memcached-adapter": "^0.3.1"
```
