### ISSUE TITLE
Adapter bundle does not use Redis database from DSN

### ISSUE THREAD

**Issue by Amunak** [php-cache/issues#62]
This issue is that when you use DSN the number after the trailing slash is supposed to denote the Redis database to be selected for storing data, and while there are examples of configuration like this it doesn't do anything.

Example cache adapter provider configuration:
```YAML
cache_adapter:
    providers:
        default:
            factory: cache.factory.redis
            options:
                dsn: "redis://localhost/4"
```

This is supposed to connect to Redis server on `localhost` using the default port and then use database 4 (i.e. run `SELECT 4`). The latter doesn't happen.

I was able to fix this by adding this code to RedisFactory.php on line 46:
```PHP
if ($dsn->getDatabase() !== null) {
    $client->select($dsn->getDatabase());
}
```
---
As a side note: You should probably handle when this function returns `false` (and the same applies for when `$client->connect()` or `$client->auth()` fail). Currently all those errors, while potentially critical, don't get caught.

Also, [the documentation](
http://php-cache.readthedocs.io/en/latest/symfony/adapter-bundle/) does not mention DSN at all while it is a valid (and possibly the best) way to define a path to a database (or database-like) data storage.
