### ISSUE TITLE
symfony/adapter-bundle pool_namespace support?

### ISSUE THREAD

**Issue by bendavies** [php-cache/issues#79]
Hey,

I'd like to use different namespaces for each of my caches, as the cache key can colide.
Example:

```
cache_adapter:
  providers:
    customer_foo_cache:
      factory: 'cache.factory.doctrine_filesystem'
      options:
       directory: '%kernel.cache_dir%/cache'
    customer_bar_cache:
      factory: 'cache.factory.doctrine_filesystem'
      options:
       directory: '%kernel.cache_dir%/cache'
```

If i am caching `Foo` and `Bar` values for my customer, i'd like to just use the customer's ID as the cache key, but ofcourse that won't work as it'll collide between caches.

Can we either add `NamespacedCachePool` support to all cache adapters, or alternatively, enable configuring the `namespace` option for doctine adapters? obviously the former is more desirable.

Let me know if i'm missing anything obvious.

Thanks
